### ISSUE TITLE
ElementRelations breaks LinkVault plugin

### ISSUE THREAD

**Issue by belkin** [internetztube/craft-element-relations#30]
When using ElementRelations with LinkVault it breaks the plugin. If I disabled ElementRelations plugin then [LinkVault](https://plugins.craftcms.com/linkvault?craft4) works.

In the logs I see the following: 

```
2022-11-24 08:12:15 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=127.0.0.1;dbname=cr_site;port=3306 {"memory":4632416} 
2022-11-24 08:12:15 [web.INFO] [nystudio107\codeeditor\CodeEditor::bootstrap] CodeEditor module bootstrapped {"memory":7262344} 
2022-11-24 08:12:15 [web.INFO] [modules\site\Site::init] Site module loaded {"memory":7278592} 
2022-11-24 08:12:15 [web.INFO] [presseddigital\linkit\Linkit::init] Linkit plugin loaded {"memory":7785544} 
2022-11-24 08:12:15 [web.INFO] [vaersaagod\matrixmate\MatrixMate::init] MatrixMate plugin loaded {"memory":7878728} 
2022-11-24 08:12:15 [web.INFO] [wrav\oembed\Oembed::init] oEmbed plugin loaded {"memory":7916016} 
2022-11-24 08:12:15 [web.INFO] [nystudio107\retour\Retour::init] Retour plugin loaded {"memory":7977416} 
2022-11-24 08:12:15 [web.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":8354632} 
2022-11-24 08:12:15 [web.INFO] [yii\web\Session::open] Session started {"memory":8450208} 
2022-11-24 08:12:15 [web.ERROR] [yii\base\ErrorException:2] yii\base\ErrorException: Attempt to read property "id" on null in /site/vendor/internetztube/craft-element-relations/src/ElementRelations.php:97
Stack trace:
#0 /sitevendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Attempt to read...', '/site/D...', 97)
#1 /site/vendor/internetztube/craft-element-relations/src/ElementRelations.php(97): craft\web\ErrorHandler->handleError(2, 'Attempt to read...', '/site/D...', 97)
#2 [internal function]: internetztube\elementRelations\ElementRelations->internetztube\elementRelations\{closure}(Object(craft\events\Model
```

So somehow ElementRelations is triggered there while trying download a file.

Craft version: 4.3.3
Plugin version: 2.0.2
LinkVault version: 4.0.1

**Comment by internetztube** [comment]
This should be fixed with the latest release. Thank you!
